CREATE OR REPLACE PROCEDURE DISHA_MART_ANALYTICS.COLLECTION_MART.LOAD_DELINQUENCY_MART("RUN_DATE" DATE)
RETURNS VARCHAR(255)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'DECLARE
    -- Logging Variables
	PROC_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.COLLECTION_MART.LOAD_DELINQUENCY_MART'';
	TBL_NAME VARCHAR(500):=''DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART'';
    TOTAL_ROWS_IN_PREFINAL INTEGER;
    ROWS_INSERTED INTEGER DEFAULT 0;
    ROWS_UPDATED INTEGER DEFAULT 0;
    ROWS_UNCHANGED INTEGER DEFAULT 0;
    DUPLICATE_COUNT INTEGER;
    DUPLICATE_DETAILS VARCHAR(2000);
    CURR_TIME TIMESTAMP := TO_VARCHAR(CURRENT_TIMESTAMP());
    ERROR_MESSAGE VARCHAR;
    FINAL_OUTPUT VARCHAR(4000);
	 
	-- Variables for dynamic column handling and update with hashcolumn list in create and below variable
    	    -- Variables for dynamic column handling
        INSERT_COLUMN_LIST VARCHAR;
        HASH_COLUMN_LIST  VARCHAR:=''S.LOAN_NO, S.CUSTOMER_ID, S.MORATORIUM, S.CHEQUE_IN_TRANSIT_AMT, S.CHEQUE_IN_TRANSIT_COUNT, S.OVERDUE_PRINCIPAL, S.OVERDUE_INTEREST, S.TOTAL_DUE, S.REMAINING_TENURE, S.PENAL_AMOUNT_OUTSTANDING,S.OP_DPD, S.COLLX_BKT,S.CYCLE,S.CURRENT_DPD_SCALE,S.OP_DPD_SCALE,S.CURRENT_STATUS,S.STATUS,S.PAID_STATUS,S.CYCLE_DATE,S.ON_OFF_BOOK,S.INSTALLMENT_MODE,S.LOAN_SANCTION_DATE,S.NET_LTV,S.EMI_OVERDUE_AMOUNT,S.BUSINESS_BRANCH,S.BUSINESS_STATE,S.COLLECTION_AGENT_EMP_ID, S.VERTICAL,S.LAST_RECEIPT_AMOUNT,S.LAST_RECEIVED_DATE_KNOCKOFF_DATE,S.BRANCH_ID,S.PRODUCT_ID'';
        INSERT_VALUE_LIST VARCHAR;
    
	
    -- SQL statements to execute
    MERGE_STATEMENT VARCHAR(16000);
    INSERT_STATEMENT VARCHAR(16000);
	UPDATE_STATEMENT VARCHAR(16000);
	
	BEGIN

CREATE TABLE IF NOT EXISTS DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART
(
LOAN_NO VARCHAR(255),
LOAN_AMOUNT FLOAT,
LOAN_BUCKET_VALUE VARCHAR(255),
CUSTOMER_ID VARCHAR(255),
MORATORIUM INTEGER,
CHEQUE_IN_TRANSIT_AMT FLOAT,
CHEQUE_IN_TRANSIT_COUNT FLOAT,
OVERDUE_PRINCIPAL FLOAT,
OVERDUE_INTEREST FLOAT,
TOTAL_DUE FLOAT,
REMAINING_TENURE FLOAT,
PENAL_AMOUNT_OUTSTANDING FLOAT,
COLL_NPA_LOAN VARCHAR(255),
REPORTED_DPD VARCHAR(255),
AFS_LOAN VARCHAR(255),
ENCORE_LOAN VARCHAR(255),
WRITEOFF_LOAN VARCHAR(255),
OP_DPD VARCHAR(255),
COLLX_BKT VARCHAR(255),
TICKET VARCHAR(255),
CYCLE VARCHAR(255),
CURRENT_DPD_SCALE VARCHAR(255),
OP_DPD_SCALE VARCHAR(255),
CURRENT_STATUS VARCHAR(255),
STATUS VARCHAR(255),
PAID_STATUS VARCHAR(255),
BUSINESS_DATE DATE,
CYCLE_DATE VARCHAR(255),
ON_OFF_BOOK VARCHAR(255),
INSTALLMENT_MODE VARCHAR(255),
LOAN_SANCTION_DATE DATE,
NET_LTV FLOAT,
EMI_OVERDUE_AMOUNT FLOAT,
BUSINESS_BRANCH VARCHAR(255),
BUSINESS_STATE VARCHAR(255),
VERTICAL VARCHAR(255),
BUCKET_HEAD VARCHAR(255),
LAST_RECEIPT_AMOUNT  FLOAT,
LAST_RECEIVED_DATE_KNOCKOFF_DATE DATE,
BRANCH_ID INTEGER,
BRANCH_NAME VARCHAR(255),
BRANCH_STATE VARCHAR(255),
BRANCH_VINTAGE_MONTHS INTEGER,
BRANCH_VINTAGE_BUCKET VARCHAR(255),
PRODUCT_ID INTEGER,
PRODUCT_CATEGORY VARCHAR(255),
PRODUCT_NAME VARCHAR(255),
COLLECTION_AGENT_EMP_ID VARCHAR(255),
COLLECTION_RESPONSIBILITY VARCHAR(255),
TEAM VARCHAR(255),
COLL_TL_EMP_ID VARCHAR(255),
COLL_TL VARCHAR(255),
COLL_ACM_EMP_ID VARCHAR(255),
COLL_ACM VARCHAR(255),
COLL_SH_EMP_ID VARCHAR(255),
COLL_SH_NPL VARCHAR(255),
COLL_ZH_EMP_ID VARCHAR(255),
COLL_COLL_ZH VARCHAR(255),
COLL_AFFORDABLE_ACM_EMP_ID VARCHAR(255),
COLL_AFFORDABLE_ACM VARCHAR(255),
COLL_NH_EMP_ID VARCHAR(255),
COLL_NH VARCHAR(255),
COLL_BH_EMP_ID VARCHAR(255),
COLL_BH  VARCHAR(255),
SALES_EMPLOYEE_ID VARCHAR(255),
SALES_EMPLOYEE_NAME  VARCHAR(255),
SALES_BSM_ID  VARCHAR(255),
SALES_BSM_NAME VARCHAR(255),
SALES_PM_ID VARCHAR(255),
SALES_PM_NAME  VARCHAR(255),
SALES_BH_ID  VARCHAR(255),
SALES_BH_NAME  VARCHAR(255),
SALES_SH_ID  VARCHAR(255),
SALES_SH_NAME VARCHAR(255),
SALES_ZH_ID  VARCHAR(255),
SALES_ZH_NAME  VARCHAR(255),
SALES_NSM_ID  VARCHAR(255),
SALES_NSM_NAME  VARCHAR(255),
SALES_VH_ID VARCHAR(255),
SALES_VH_NAME VARCHAR(255),
SALES_BSH_ID  VARCHAR(255),
SALES_BSH_NAME VARCHAR(255),
CREDIT_ACM_ID VARCHAR(255),
CREDIT_ACM_NAME VARCHAR(255),
CREDIT_SCM_ID VARCHAR(255),
CREDIT_SCM_NAME VARCHAR(255),
CREDIT_ZCM_ID VARCHAR(255),
CREDIT_ZCM_NAME VARCHAR(255),
CREDIT_ZCH_ID VARCHAR(255),
CREDIT_ZCH_NAME VARCHAR(255),
CREDIT_NCH_ID VARCHAR(255),
CREDIT_NCH_NAME VARCHAR(255),
EXTRACT_DATE VARCHAR(255),			
ACTIVATION_FLAG NUMBER(38,0),
ROW_HASH VARCHAR(255) AS (SHA2(UPPER(ARRAY_TO_STRING(ARRAY_CONSTRUCT(LOAN_NO, CUSTOMER_ID, MORATORIUM, CHEQUE_IN_TRANSIT_AMT, CHEQUE_IN_TRANSIT_COUNT, OVERDUE_PRINCIPAL, OVERDUE_INTEREST, TOTAL_DUE, REMAINING_TENURE, PENAL_AMOUNT_OUTSTANDING, OP_DPD, COLLX_BKT,CYCLE,CURRENT_DPD_SCALE,OP_DPD_SCALE,CURRENT_STATUS,STATUS,PAID_STATUS,CYCLE_DATE,ON_OFF_BOOK,INSTALLMENT_MODE,LOAN_SANCTION_DATE,NET_LTV,EMI_OVERDUE_AMOUNT,BUSINESS_BRANCH,BUSINESS_STATE,COLLECTION_AGENT_EMP_ID,VERTICAL,LAST_RECEIPT_AMOUNT,LAST_RECEIVED_DATE_KNOCKOFF_DATE,BRANCH_ID,PRODUCT_ID), ''|'')), 256)),
START_TIMESTAMP TIMESTAMP_NTZ(9),
END_TIMESTAMP TIMESTAMP_NTZ(9),
CURRENT_FLAG BOOLEAN
);




CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd AS
SELECT * FROM
DISHA_L2_CURATED.HISTORICAL_LOAD.COLL_DUELIST where TRY_TO_DATE(EXTRACTED_DATE, ''YYYY-MM-DD'') = :RUN_DATE;






CREATE  OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd_with_bd AS
SELECT 
    *,
    TRY_TO_DATE(EXTRACTED_DATE, ''YYYY-MM-DD'') - 1 AS BUSINESS_DATE -- 09-09-2024
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd;


CREATE  OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.business_with_prev_month_end AS
SELECT
    *,
	DATE_TRUNC(''MONTH'', BUSINESS_DATE) AS MONTH_START_DATE
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd_with_bd;




CREATE  OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.dpd_lookup AS
SELECT
    LOAN_NO,
    BUSINESS_DATE AS DPD_DATE,
    DPD AS DPD_FOR_DATE
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd_with_bd;


CREATE OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.ld AS
SELECT
    a.LOAN_NO,
    a.EXTRACTED_DATE,
    a.BUSINESS_DATE,
    a.DPD,
    a.MONTH_START_DATE,
    b.DPD AS OP_DPD
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.business_with_prev_month_end a
--LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.dpd_lookup b
LEFT JOIN (select loan_no, DPD, EXTRACTED_DATE from DISHA_L2_CURATED.HISTORICAL_LOAD.COLL_DUELIST 
where EXTRACTED_DATE = DATE_TRUNC(''MONTH'',(TO_DATE(:RUN_DATE)-1)))  b
     ON a.LOAN_NO = b.LOAN_NO AND a.MONTH_START_DATE = b.EXTRACTED_DATE;


CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.lad_deduped AS (
  SELECT *
  FROM (
    SELECT *
    FROM DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS
    WHERE activation_flag = 1
    QUALIFY ROW_NUMBER() OVER (PARTITION BY loan_no ORDER BY dat_start DESC) = 1
  )
);

-- Step 2: Join temp_deduped_cd with the deduped LAD table
CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.cust_loan_check AS
SELECT 
  lad.CUST_ID_FLEX,
  cd.LOAN_NO,
  COUNT(DISTINCT cd.LOAN_NO) AS loan_count
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd cd
LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.lad_deduped lad 
  ON TRIM(CAST(cd.LOAN_NO AS VARCHAR)) = TRIM(lad.LOAN_NO)
GROUP BY lad.CUST_ID_FLEX, cd.LOAN_NO;


CREATE OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.collection_npa_check AS  
select *, CASE WHEN FLG_ACCR_STATUS=''S'' THEN 1 ELSE 0 END AS NPA_LOAN 
 from DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS  WHERE TO_DATE(start_date) <= :RUN_DATE 
  AND (TO_DATE(end_date) > :RUN_DATE OR TO_DATE(end_date) IS NULL) ;


CREATE OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.npa_check AS  
Select * , 
CASE WHEN DPD_90PLUS_FLAG=1 and MAXIMUM_DPD <= 90 THEN 91 ELSE MAXIMUM_DPD 
END AS REPORTED_DPD 
from
(select *, CASE WHEN FLG_ACCR_STATUS=''S'' THEN 1 ELSE 0 END AS DPD_90PLUS_FLAG 
 from DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS  WHERE TO_DATE(start_date) <= :RUN_DATE 
  AND (TO_DATE(end_date) > :RUN_DATE OR TO_DATE(end_date) IS NULL)  ) where loan_status IN (''10'',''8'',''6'') ; 

 
 CREATE OR REPLACE TEMP TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.WRITEOFF_DETAILS AS  
  select * from  DISHA_MART_ANALYTICS.CREDIT_RISK_MART.RISK_LOAN_ACCOUNT_MART_DIM 
  where TO_DATE(start_timestamp) <= :RUN_DATE AND (TO_DATE(end_timestamp) > :RUN_DATE OR TO_DATE(end_timestamp) IS NULL)  ;

CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.ro_check AS 
select 
lam.loan_no,
lam.employee_code,
SHM.*
from
( select * from DISHA_MART_ANALYTICS.SALES_CREDIT_MART.loan_application_mart where activation_flag = 1 ) lam left join
(SELECT * FROM DISHA_MART_ANALYTICS.SALES_CREDIT_MART.SALES_HIERARCHY_MART ) SHM ON 
TRIM(lam.employee_code)=TRIM(SHM.EMPLOYEE_ID) AND ((lam.DEAL_FORWARD_DATE > SHM.START_TIMESTAMP AND lam.DEAL_FORWARD_DATE  < SHM.END_TIMESTAMP) 
OR (lam.DEAL_FORWARD_DATE  > SHM.START_TIMESTAMP AND SHM.END_TIMESTAMP IS NULL));


CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.credit_hierarchy AS
select 
lam.loan_no,
lam.employee_code,
coalesce(kch.acm_id,kch1.acm_id) as acm_id,
coalesce(kch.acm_name,kch1.acm_name) as acm_name,
coalesce(kch.scm_id,kch1.scm_id) as scm_id,
coalesce(kch.scm_name,kch1.scm_name) as scm_name,
coalesce(kch.zcm_id,kch1.zcm_id) as zcm_id,
coalesce(kch.zcm_name,kch1.zcm_name) as zcm_name,
coalesce(kch.zch_id,kch1.zch_id) as zch_id,
coalesce(kch.zch_name,kch1.zch_name) as zch_name,
coalesce(kch.nch_id,kch1.nch_id) as nch_id,
coalesce(kch.nch_name,kch1.nch_name) as nch_name		 
 from 
 (select * from DISHA_MART_ANALYTICS.SALES_CREDIT_MART.loan_application_mart where activation_flag=1 ) lam
  LEFT JOIN DISHA_MART_ANALYTICS.SALES_CREDIT_MART.KYVOS_CREDIT_HIER  kch on kch.loan_application_name_s=lam.loan_application_name and 
kch.deal_id =lam.loan_application_no and kch.source_d<>''SFDC'' AND lam.DATA_SOURCE<>''SFDC'' 
LEFT JOIN DISHA_MART_ANALYTICS.SALES_CREDIT_MART.KYVOS_CREDIT_HIER  kch1 on kch1.loan_application_name_s=lam.loan_application_name 
and kch1.source_d=''SFDC'' AND lam.DATA_SOURCE=''SFDC''  ;





 CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.max_pending_emi_per_cust AS 
					SELECT 
						lad.CUST_ID_FLEX,
						cd.loan_no,
						MAX(cd.TOTAL_NO_OF_INSTL - cd.TOTAL_BILLED_INSTL_NO) AS NET_LTV
						FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd cd
						LEFT JOIN DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS lad 
						ON TRIM(CAST(cd.LOAN_NO AS VARCHAR)) = TRIM(lad.LOAN_NO) where  lad.activation_flag = 1
					GROUP BY lad.CUST_ID_FLEX , cd.loan_no;




CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.customers_with_mixed_dpd AS
SELECT 
  lad.CUST_ID_FLEX AS CUSTOMER_CODE
FROM DISHA_MART_ANALYTICS.COLLECTION_MART.ld dpd
JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd cd ON dpd.LOAN_NO = cd.LOAN_NO
LEFT JOIN DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS lad 
  ON TRIM(CAST(cd.LOAN_NO AS VARCHAR)) = TRIM(lad.LOAN_NO) and lad.activation_flag = 1
WHERE lad.CUST_ID_FLEX IS NOT NULL
GROUP BY lad.CUST_ID_FLEX
HAVING 
  MAX(CASE WHEN dpd.DPD > 0 THEN 1 ELSE 0 END) = 1 AND  MAX(CASE WHEN dpd.DPD = 0 THEN 1 ELSE 0 END) = 1;


CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.current_status_cte AS 
  SELECT 
    cd.LOAN_NO,
    cd.DPD,
    cd.CHEQUE_IN_TRANSIT_COUNT,
    ld.OP_DPD,
	cd.EXTRACTED_DATE,
    CASE 
      WHEN ld.OP_DPD >= 91 AND cd.DPD < 91 AND cd.DPD > 0 THEN ''RTD''
      WHEN cd.DPD = 0 THEN ''NORMAL''
      WHEN  cd.DPD < ld.OP_DPD AND (ld.OP_DPD - cd.DPD) < 30 THEN ''STABLE''
      WHEN cd.DPD < ld.OP_DPD THEN ''ROLLBACK''
      ELSE ''ROLLFORWARD''
    END AS CURRENT_STATUS
  FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd cd
LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.ld ld ON cd.LOAN_NO = ld.LOAN_NO and cd.EXTRACTED_DATE = ld.EXTRACTED_DATE;





CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.ch_union_raw AS (
    SELECT
 TRIM(CAST(NEW_LOAN_NO AS VARCHAR)) AS NEW_LOAN_NO,
    CASE 
        WHEN LOWER(TRIM(EMP_ID)) = ''pending'' THEN NULL
        ELSE TRIM(CAST(EMP_ID AS VARCHAR))
    END AS EMP_ID_CLEAN
,COLLECTION_RESPONSIBILITY
,EXECUTIVE_CATEGORY
,TEAM
,CASE WHEN TRIM(TL_EMP_ID) = ''NA'' then '''' end as TL_EMP_ID
,TL
,TL_NPL
,CASE WHEN TRIM(ACM_EMP_ID) = ''NA'' then '''' end as ACM_EMP_ID
,ACM
,CASE WHEN TRIM(SH_EMP_ID) = ''NA'' then '''' end as SH_EMP_ID
,SH_NPL
,CASE WHEN TRIM(ZH_EMP_ID) = ''NA'' then '''' end as ZH_EMP_ID
,COLL_ZH
,CASE WHEN TRIM(AFFORDABLE_ACM_EMP_ID) = ''NA'' then '''' end as AFFORDABLE_ACM_EMP_ID
,AFFORDABLE_ACM
,CASE WHEN TRIM(affordable_zh_emp_id) = ''NA'' then '''' end as affordable_zh_emp_id
,AFFORDABLE_ZH
,TRIM(CAST(NH_EMP_ID AS VARCHAR)) AS NH_EMP_ID
,NH
,TRIM(CAST(BH_EMP_ID AS VARCHAR))  AS BH_EMP_ID
,BH
,TRY_TO_DATE(extract_date, ''DD-MM-YYYY'') AS EXTRACT_DT
,NULL as activation_flag
    FROM DISHA_L2_CURATED.BASE_MODEL_DATA.COLL_HIERARCHY
    WHERE TRY_TO_DATE(EXTRACT_DATE, ''DD-MM-YYYY'') <= ''2025-10-05''

    UNION ALL
    SELECT
TRIM(CAST(NEW_LOAN_NO AS VARCHAR)) AS NEW_LOAN_NO,
TRIM(CAST(EMP_ID AS VARCHAR)) AS EMP_ID
,COLLECTION_RESPONSIBILITY
,EXECUTIVE_CATEGORY
,TEAM
,CASE WHEN TRIM(TL_EMP_ID) = ''NA'' then '''' end as TL_EMP_ID 
,TL
,TL_NPL
,CASE WHEN TRIM(ACM_EMP_ID) = ''NA'' then '''' end as  ACM_EMP_ID
,ACM
,CASE WHEN TRIM(SH_EMP_ID) = ''NA'' then '''' end as   SH_EMP_ID
,SH_NPL
,CASE WHEN TRIM(ZH_EMP_ID) = ''NA'' then '''' end as    ZH_EMP_ID
,COLL_ZH
,CASE WHEN TRIM(AFFORDABLE_ACM_EMP_ID) = ''NA'' then '''' end as     AFFORDABLE_ACM_EMP_ID
,AFFORDABLE_ACM
,'''''''' AS affordable_zh_emp_id
,AFFORDABLE_ZH
,TRIM(CAST(NH_EMP_ID AS VARCHAR)) AS NH_EMP_ID
,NH
,TRIM(CAST(BH_EMP_ID AS VARCHAR))  AS BH_EMP_ID
,BH
,COALESCE(
            TRY_TO_DATE(EXTRACT_DATE, ''YYYY-MM-DD''),
            TRY_TO_DATE(EXTRACT_DATE, ''DD-MM-YYYY'')
        ) AS EXTRACT_DT,       
        activation_flag
    FROM DISHA_L2_CURATED.MANUAL_INGESTION_TABLES.COLLECTION_COLLECTION_HIERARCHY
    WHERE COALESCE(
            TRY_TO_DATE(EXTRACT_DATE, ''YYYY-MM-DD''),
            TRY_TO_DATE(EXTRACT_DATE, ''DD-MM-YYYY'')
          ) >= ''2025-10-06'');


CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.ch_dedup AS (
    SELECT *
    FROM (
        SELECT
				*,
            ROW_NUMBER() OVER (
                PARTITION BY NEW_LOAN_NO, EXTRACT_DT
                ORDER BY EXTRACT_DT DESC
            ) AS rn
        FROM DISHA_MART_ANALYTICS.COLLECTION_MART.ch_union_raw
    )
    WHERE rn = 1
);


CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.ch_effective AS (
    SELECT
       *,
        CASE
            WHEN EXTRACT_DT <= ''2025-09-30''
                THEN DATE_TRUNC(''MONTH'', EXTRACT_DT) + INTERVAL ''1 MONTH'' - INTERVAL ''1 DAY''
            ELSE EXTRACT_DT
        END AS EFFECTIVE_EXTRACT_DATE
    FROM DISHA_MART_ANALYTICS.COLLECTION_MART.ch_dedup
);




CREATE OR REPLACE TEMPORARY TABLE DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL 
(
LOAN_NO VARCHAR(255),
LOAN_AMOUNT FLOAT,
LOAN_BUCKET_VALUE VARCHAR(255),
CUSTOMER_ID VARCHAR(255),
MORATORIUM INTEGER,
CHEQUE_IN_TRANSIT_AMT FLOAT,
CHEQUE_IN_TRANSIT_COUNT FLOAT,
OVERDUE_PRINCIPAL FLOAT,
OVERDUE_INTEREST FLOAT,
TOTAL_DUE FLOAT,
REMAINING_TENURE FLOAT,
PENAL_AMOUNT_OUTSTANDING FLOAT,
COLL_NPA_LOAN VARCHAR(255),
REPORTED_DPD VARCHAR(255),
AFS_LOAN VARCHAR(255),
ENCORE_LOAN VARCHAR(255),
WRITEOFF_LOAN VARCHAR(255),
OP_DPD VARCHAR(255),
COLLX_BKT VARCHAR(255),
TICKET VARCHAR(255),
CYCLE VARCHAR(255),
CURRENT_DPD_SCALE VARCHAR(255),
OP_DPD_SCALE VARCHAR(255),
CURRENT_STATUS VARCHAR(255),
STATUS VARCHAR(255),
PAID_STATUS VARCHAR(255),
BUSINESS_DATE DATE,
CYCLE_DATE VARCHAR(255),
ON_OFF_BOOK VARCHAR(255),
INSTALLMENT_MODE VARCHAR(255),
LOAN_SANCTION_DATE DATE,
NET_LTV FLOAT,
EMI_OVERDUE_AMOUNT FLOAT,
BUSINESS_BRANCH VARCHAR(255),
BUSINESS_STATE VARCHAR(255),
VERTICAL VARCHAR(255),
BUCKET_HEAD VARCHAR(255),
LAST_RECEIPT_AMOUNT  FLOAT,
LAST_RECEIVED_DATE_KNOCKOFF_DATE DATE,
BRANCH_ID INTEGER,
BRANCH_NAME VARCHAR(255),
BRANCH_STATE VARCHAR(255),
BRANCH_VINTAGE_MONTHS INTEGER,
BRANCH_VINTAGE_BUCKET VARCHAR(255),
PRODUCT_ID INTEGER,
PRODUCT_CATEGORY VARCHAR(255),
PRODUCT_NAME VARCHAR(255),
COLLECTION_AGENT_EMP_ID VARCHAR(255),
COLLECTION_RESPONSIBILITY VARCHAR(255),
TEAM VARCHAR(255),
COLL_TL_EMP_ID VARCHAR(255),
COLL_TL VARCHAR(255),
COLL_ACM_EMP_ID VARCHAR(255),
COLL_ACM VARCHAR(255),
COLL_SH_EMP_ID VARCHAR(255),
COLL_SH_NPL VARCHAR(255),
COLL_ZH_EMP_ID VARCHAR(255),
COLL_COLL_ZH VARCHAR(255),
COLL_AFFORDABLE_ACM_EMP_ID VARCHAR(255),
COLL_AFFORDABLE_ACM VARCHAR(255),
COLL_NH_EMP_ID VARCHAR(255),
COLL_NH VARCHAR(255),
COLL_BH_EMP_ID VARCHAR(255),
COLL_BH  VARCHAR(255),
SALES_EMPLOYEE_ID VARCHAR(255),
SALES_EMPLOYEE_NAME  VARCHAR(255),
SALES_BSM_ID  VARCHAR(255),
SALES_BSM_NAME VARCHAR(255),
SALES_PM_ID VARCHAR(255),
SALES_PM_NAME  VARCHAR(255),
SALES_BH_ID  VARCHAR(255),
SALES_BH_NAME  VARCHAR(255),
SALES_SH_ID  VARCHAR(255),
SALES_SH_NAME VARCHAR(255),
SALES_ZH_ID  VARCHAR(255),
SALES_ZH_NAME  VARCHAR(255),
SALES_NSM_ID  VARCHAR(255),
SALES_NSM_NAME  VARCHAR(255),
SALES_VH_ID VARCHAR(255),
SALES_VH_NAME VARCHAR(255),
SALES_BSH_ID  VARCHAR(255),
SALES_BSH_NAME VARCHAR(255),
CREDIT_acm_id VARCHAR(255),
CREDIT_acm_name VARCHAR(255),
CREDIT_scm_id VARCHAR(255),
CREDIT_scm_name VARCHAR(255),
CREDIT_zcm_id VARCHAR(255),
CREDIT_zcm_name VARCHAR(255),
CREDIT_zch_id VARCHAR(255),
CREDIT_zch_name VARCHAR(255),
CREDIT_nch_id VARCHAR(255),
CREDIT_nch_name VARCHAR(255),
EXTRACT_DATE VARCHAR(255)
)
AS 
SELECT 
			TRIM(CAST(cd.LOAN_NO AS VARCHAR)),
			lad.loan_sanction_amount,
            loan_bkt.bucket_values,			
			TRIM(lad.CUST_ID_FLEX),
			cd.MORATORIUM,
			cd.CHEQUE_IN_TRANSIT_AMT,
			cd.CHEQUE_IN_TRANSIT_COUNT,
			cd.OVERDUE_PRIN,
			cd.OVERDUE_INTEREST,
			cd.TOTAL_DUE,
			(cd.TOTAL_NO_OF_INSTL - cd.TOTAL_BILLED_INSTL_NO) AS REMAINING_TENURE,
			(cd.LPP + cd.CBC_DUE + cd.OTHER_CHARGES_DUE) AS PENAL_AMOUNT_OUTSTANDING,
			cnc.npa_loan as COLL_NPA_LOAN,
			npa_check.REPORTED_DPD	AS REPORTED_DPD,
			CASE WHEN AFS_OMNI.LOAN_NO IS NOT NULL THEN 1 ELSE 0 END AS AFS_LOAN,
			CASE WHEN ENCORE_OMNI.LOAN_NO IS NOT NULL THEN 1 ELSE 0 END AS ENCORE_LOAN,
			CASE WHEN TRIM(WD.WRITEOFF_FLAG)=''1'' THEN 1 ELSE 0 END AS WRITEOFF_LOAN,
			ld.OP_DPD AS OP_DPD,
			CASE 
			  WHEN ld.OP_DPD = 0 THEN ''A:0-0''
			  WHEN ld.OP_DPD >= 1 AND ld.OP_DPD <= 30 THEN ''B:1-30''
			  WHEN ld.OP_DPD >= 31 AND ld.OP_DPD <= 60 THEN ''C:31-60''
			  WHEN ld.OP_DPD >= 61 AND ld.OP_DPD <= 90 THEN ''D:61-90''
			  WHEN ld.OP_DPD >= 91 AND ld.OP_DPD <= 120 THEN ''E:91-120''
			  WHEN ld.OP_DPD >= 121 AND ld.OP_DPD <= 180 THEN ''F:121-180''
			  WHEN ld.OP_DPD > 180 THEN ''G:180''
			END AS COLLX_BKT,
			CASE 
				WHEN cd.TOTAL_POS <= 700000 then ''STS''
				WHEN cd.TOTAL_POS > 700001 AND cd.TOTAL_POS <= 1500000 then ''MTS''
				WHEN cd.TOTAL_POS > 1500001 AND cd.TOTAL_POS <= 2500000 then ''HTS''
			ELSE ''SHTS'' 
			END AS TICKET,	
			CASE 
			  WHEN ld.OP_DPD != 0 THEN ''Opening Allocation''
			  WHEN ld.OP_DPD = 0 AND DAY(TRY_TO_DATE(cd.LAST_EMI_DATE, ''YYYY-MM-DD'')) = 5 THEN ''5th Cycle''
			  WHEN ld.OP_DPD = 0 AND DAY(TRY_TO_DATE(cd.LAST_EMI_DATE, ''YYYY-MM-DD'')) = 10 THEN ''10th Cycle''
			  WHEN ld.OP_DPD = 0 AND DAY(TRY_TO_DATE(cd.LAST_EMI_DATE, ''YYYY-MM-DD'')) = 15 THEN ''15th Cycle''
			  ELSE ''NA''
			END AS Cycle,
			CASE 
				WHEN cd.DPD = 0 THEN ''A:0-0''
				WHEN cd.DPD >= 1 AND  	cd.DPD <= 30 THEN ''B:1-30''
				WHEN cd.DPD >= 31 AND 	cd.DPD <= 60 THEN ''C:31-60''
				WHEN cd.DPD >= 61 AND 	cd.DPD <= 90 THEN ''D:61-90''
				WHEN cd.DPD >= 91 AND 	cd.DPD <= 120 THEN ''E:91-120''
				WHEN cd.DPD >= 121 AND cd.DPD <= 180 THEN ''F:121-180''
				WHEN cd.DPD > 180 THEN ''G:180''		
			END AS CURRENT_DPD_SCALE,
			CASE 
			  WHEN AFS_LOAN = 1 THEN ''AFS''
			  WHEN npa_check.REPORTED_DPD > 90 THEN ''NPA''
			  WHEN npa_check.REPORTED_DPD > 90 and cd.DPD <= 90 THEN ''linked loan NPA''
			  WHEN AFS_LOAN = 1 AND npa_check.REPORTED_DPD > 90 THEN ''NPA AFS''
			  WHEN (AFS_LOAN = 1 OR  npa_check.REPORTED_DPD > 90 OR npa_check.REPORTED_DPD = 90 and cd.DPD <= 90 ) AND cd.DPD = 0 THEN ''OUT OF NPA''
				END AS OP_DPD_SCALE,
			cs.CURRENT_STATUS,
			CASE WHEN cs.CURRENT_STATUS = ''ROLLFORWARD'' and TRY_TO_NUMBER(cd.CHEQUE_IN_TRANSIT_COUNT) <> 0 then ''Cheque in transit''
			ELSE cs.CURRENT_STATUS END as STATUS,
			CASE WHEN STATUS IN (''ROLLFORWARD'',''Cheque in transit'') then ''Unpaid''
			ELSE ''Paid'' END AS PAID_STATUS,
			DATEADD(DAY,-1,TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD'')) AS BUSINESS_DATE,
			CASE 
			  WHEN DAY(TRY_TO_DATE(cd.LAST_EMI_DATE,''YYYY-MM-DD'')) = 5 THEN 5 
			  WHEN DAY(TRY_TO_DATE(cd.LAST_EMI_DATE,''YYYY-MM-DD'')) = 10 THEN 10 
			  WHEN DAY(TRY_TO_DATE(cd.LAST_EMI_DATE,''YYYY-MM-DD'')) = 15 THEN 15 
			END AS CYCLE_DATE,
			CASE 
			WHEN laae.POOL_NAME IS NULL then ''ON-BOOK''
			WHEN laae.POOL_NAME like ''%PTC%'' then ''PTC''
			ELSE ''OFF-BOOK''
			END AS ON_OFF_BOOK,
   			lac.repayment_mode__c AS INSTALLMENT_MODE, 
			lad.LOAN_SANCTION_DATE,
			max_pending_emi_per_cust.NET_LTV AS NET_LTV,
			(cd.TOTAL_DUE + cd.PRE_EMI) AS EMI_OVERDUE_AMOUNT,	
			shm.BUSINESS_BRANCH,
			shm.business_state,
			SHM.VERTICAL,			
			CASE 
				WHEN SHM.VERTICAL like ''AFFORDABLE'' OR  (SHM.VERTICAL like ''MSME'' and TICKET like ''STS'') then ''AFFORDABLE & MSME'' 
				WHEN COLLX_BKT like ''A:0-0'' then ''FLOW''
				WHEN COLLX_BKT like ''B:1-30'' OR COLLX_BKT like ''C:31-60'' OR COLLX_BKT like ''D:61-90'' then ''GCL''
			ELSE ''NPL'' END AS BUCKET_HEAD,	
			cd.LAST_RECEIPT_AMOUNT,
			cd.LAST_RECEIVED_DATE_KNOCKOFF_DATE,
            bd.branch_lms_code AS BRANCH_ID,
            cd.loan_branch AS BRANCH_NAME,
			cd.state AS BRANCH_STATE,
            datediff(''MONTH'',bd.date_of_opening,current_Date) ,
            branch_bkt.bucket_values AS BRANCH_VINTAGE_BUCKET, 				
			LAAD.COD_PROD AS PRODUCT_ID,
			pm.PRODUCT_CATEGORY AS PRODUCT_CATEGORY,
			pm.product_name AS PRODUCT_NAME,
			ch.EMP_ID_CLEAN,
			ch.COLLECTION_RESPONSIBILITY,
			ch.TEAM,
			ch.TL_EMP_ID,
			ch.TL,
			ch.ACM_EMP_ID,
			ch.ACM,
			ch.SH_EMP_ID,
			ch.SH_NPL,
			ch.ZH_EMP_ID,
			ch.COLL_ZH,
			ch.AFFORDABLE_ACM_EMP_ID,
			ch.AFFORDABLE_ACM,
			ch.NH_EMP_ID,
			ch.NH,
			ch.BH_EMP_ID,
			ch.BH, 
			ro_check.EMPLOYEE_ID,
			ro_check.EMPLOYEE_NAME,
			ro_check.BSM_ID,
			ro_check.BSM_NAME,
			ro_check.PM_ID,
			ro_check.PM_NAME,
			ro_check.BH_ID,
			ro_check.BH_NAME,
			ro_check.SH_ID,
			ro_check.SH_NAME,
			ro_check.ZH_ID,
			ro_check.ZH_NAME,
			ro_check.NSM_ID,
			ro_check.NSM_NAME,
			ro_check.VH_ID,
			ro_check.VH_NAME,
			ro_check.BSH_ID,
			ro_check.BSH_NAME,
			chm.acm_id,
			chm.acm_name,
			chm.scm_id,
			chm.scm_name,
			chm.zcm_id,
			chm.zcm_name,
			chm.zch_id,
			chm.zch_name,
			chm.nch_id,
			chm.nch_name,
			ch.EFFECTIVE_EXTRACT_DATE
			FROM DISHA_MART_ANALYTICS.COLLECTION_MART.temp_deduped_cd cd
		LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.collection_npa_check cnc ON 	TRIM(cd.LOAN_NO) = TRIM(cnc.LOAN_NO)
		LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.npa_check ON TRIM(cd.LOAN_NO) = TRIM(npa_check.LOAN_NO)
		LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.WRITEOFF_DETAILS WD ON TRIM(cd.loan_no) = TRIM(WD.LOAN_NO)
        LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.ld ld ON TRIM(cd.LOAN_NO) = TRIM(ld.LOAN_NO) and cd.EXTRACTED_DATE = ld.EXTRACTED_DATE
		LEFT JOIN (select distinct loan_no from DISHA_L2_CURATED.HISTORICAL_LOAD.AFS_SINCE_APR16) AFS_OMNI ON TRIM(substring(cd.LOAN_NO,9,6))=TRIM(right(AFS_OMNI.LOAN_NO,6))
    	LEFT JOIN (select distinct loan_no from DISHA_L2_CURATED.HISTORICAL_LOAD.ENCORE_DATA) ENCORE_OMNI ON TRIM(cd.LOAN_NO)=TRIM(ENCORE_OMNI.LOAN_NO)
        LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.current_status_cte cs ON cd.LOAN_NO = cs.LOAN_NO	AND cd.EXTRACTED_DATE = cs.EXTRACTED_DATE
     	LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.ro_check ro_check ON TRIM(cd.LOAN_NO) = TRIM(ro_check.loan_no)  
        LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.credit_hierarchy chm ON TRIM(cd.LOAN_NO) = TRIM(chm.LOAN_NO)
        LEFT JOIN (select * from DISHA_L1_HARMONIZED.FLEX_LMS.LN_ACCT_ATTRIBUTES_EXT where activation_flag = 1) laae ON TRIM(cd.LOAN_NO) = TRIM(laae.COD_ACCT_NO) 
		LEFT JOIN (select * from DISHA_L1_HARMONIZED.FLEX_LMS.LN_ACCT_DTLS where activation_flag = 1 ) laad ON TRIM(cd.LOAN_NO) = TRIM(laad.cod_acct_no) 
		LEFT JOIN (select * from DISHA_L1_HARMONIZED.SFDC_LOS.loan_application__c where activation_flag = 1 ) lac ON TRIM(cd.LOAN_NO) = TRIM(lac.loan_application_id__c)
		LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.ch_effective ch
		ON TRIM(cd.LOAN_NO) = TRIM(ch.NEW_LOAN_NO)
		AND ((TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD'') <= ''2025-09-30''
		AND DATE_TRUNC(''MONTH'', DATEADD(DAY, -1, TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD''))) = DATE_TRUNC(''MONTH'', ch.EFFECTIVE_EXTRACT_DATE))
        OR (TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD'') >= ''2025-10-01'' AND TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD'') = ch.EFFECTIVE_EXTRACT_DATE ))
		--TRY_TO_DATE(cd.EXTRACTED_DATE, ''YYYY-MM-DD'') = ch.EFFECTIVE_EXTRACT_DATE
		-- AND ch.activation_flag = 1
		LEFT JOIN (SELECT * FROM DISHA_MART_ANALYTICS.SALES_CREDIT_MART.SALES_HIERARCHY_MART where CURRENT_FLAG = ''TRUE'') SHM ON 
		TRIM(ro_check.employee_code)=TRIM(SHM.EMPLOYEE_ID) 		
		LEFT JOIN (select * from DISHA_L2_CURATED.BASE_MODEL_DATA.LOAN_ACCOUNT_DETAILS where activation_flag = 1 ) lad 
        ON TRIM(CAST(cd.LOAN_NO AS VARCHAR)) = TRIM(lad.LOAN_NO)
        LEFT JOIN disha_l2_curated.base_hardcode.Config_File_Bucketing AS loan_bkt 
        ON lad.loan_sanction_amount IS NOT NULL  AND loan_bkt.bucket_name = ''Sanction_Amount_Bkt'' AND  
        ((lad.loan_sanction_amount/100000  >= loan_bkt.start_value AND lad.loan_sanction_amount/100000 < loan_bkt.end_value) OR (lad.loan_sanction_amount/100000>= loan_bkt.start_value AND loan_bkt.end_value IS NULL) )  
        LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.cust_loan_check cust_loan_check ON TRIM(cd.loan_no) = TRIM(cust_loan_check.loan_no)
        LEFT JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.max_pending_emi_per_cust  max_pending_emi_per_cust ON TRIM(cd.loan_no) = TRIM(max_pending_emi_per_cust.loan_no)
		LEFT  join (select *  from DISHA_L2_CURATED.BASE_MODEL_DATA.BRANCH_DETAILS  where activation_flag = 1) bd ON laad.cod_cc_brn = bd.branch_lms_code
        LEFT JOIN disha_l2_curated.base_hardcode.Config_File_Bucketing branch_bkt  
        ON branch_bkt.bucket_name = ''Branch_Vintage_Bkt'' 
        AND  ( ( datediff(''MONTH'',date_of_opening,current_Date)  >= branch_bkt.start_value AND datediff(''MONTH'',date_of_opening,current_Date)  < branch_bkt.end_value) 
        OR (datediff(''MONTH'',date_of_opening,current_Date) >= branch_bkt.start_value AND branch_bkt.end_value IS NULL ))
		LEFT join (select * from DISHA_L2_CURATED.BASE_MODEL_DATA.PRODUCT_MASTER ) pm ON laad.cod_prod = pm.PRODUCT_ID  ;



	SELECT COUNT(*) INTO :DUPLICATE_COUNT 
  FROM (
    SELECT LOAN_NO, COUNT(*) AS RECORD_COUNT
    FROM DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL
    GROUP BY LOAN_NO
    HAVING COUNT(*) > 1
  );

	
    
    -- Insert column list (all columns including metadata columns)
    SELECT LISTAGG(COLUMN_NAME, '','')  WITHIN GROUP (ORDER BY ORDINAL_POSITION)|| '',START_TIMESTAMP,END_TIMESTAMP,ACTIVATION_FLAG,CURRENT_FLAG''
    INTO :INSERT_COLUMN_LIST
    FROM DISHA_MART_ANALYTICS.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = ''COLLECTION_MART''
    AND TABLE_NAME = ''DELINQUENCY_MART_PREFINAL''
    AND TABLE_CATALOG = ''DISHA_MART_ANALYTICS'';
    
    -- Insert value list (dynamically mapping source columns)
    SELECT LISTAGG(''S.'' || COLUMN_NAME, '','')  WITHIN GROUP (ORDER BY ORDINAL_POSITION)
    INTO :INSERT_VALUE_LIST
    FROM DISHA_MART_ANALYTICS.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = ''COLLECTION_MART''
    AND TABLE_NAME = ''DELINQUENCY_MART_PREFINAL''
    AND TABLE_CATALOG = ''DISHA_MART_ANALYTICS'';   

    SELECT COUNT(*) INTO :TOTAL_ROWS_IN_PREFINAL
    FROM DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL ;
	--where ACTIVATION_FLAG=1;

   -- If duplicates exist, return detailed error
    IF (DUPLICATE_COUNT > 0) THEN
          SELECT CONCAT(
            ''===== DATA LOADING FAILED =====
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Duplicate Rows Found: '', :DUPLICATE_COUNT, ''
'',
            ''ERROR: Unable to load data due to duplicate entries for LOAN_NO.'',''
''
        ) INTO :FINAL_OUTPUT;
		
				--INSERT AUDIT INFO INTO TABLE
		DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		WHERE  PROCEDURE_NAME=:PROC_NAME
		AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''FAIL'',:CURR_TIME,CURRENT_TIMESTAMP;
		
		
        RETURN FINAL_OUTPUT;
    ELSE
	

              -- Perform MERGE operation with tracking
  MERGE_STATEMENT :=  CONCAT(
    ''MERGE INTO DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART T
    USING DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL S
    ON T.LOAN_NO = S.LOAN_NO 
		AND T.ACTIVATION_FLAG = 1
    WHEN MATCHED 
    AND SHA2(UPPER(ARRAY_TO_STRING(['', 
    HASH_COLUMN_LIST, 
    ''], ''''|'''')), 256) <> T.ROW_HASH
    THEN UPDATE SET 
        CURRENT_FLAG = FALSE,
        END_TIMESTAMP ='''''',:RUN_DATE,'''''',
		T.ACTIVATION_FLAG=0
    WHEN NOT MATCHED THEN 
    INSERT ('', 
    INSERT_COLUMN_LIST, 
    '')
    VALUES('', 
    INSERT_VALUE_LIST,'','''''',:RUN_DATE,'''''',NULL,1,TRUE);'');
	
	--RETURN MERGE_STATEMENT;
	EXECUTE IMMEDIATE :MERGE_STATEMENT;

        -- Count rows affected
         ROWS_INSERTED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART WHERE ACTIVATION_FLAG=1 and START_TIMESTAMP=:RUN_DATE);
         ROWS_UPDATED := (SELECT COUNT(*) FROM DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART WHERE ACTIVATION_FLAG=0 and END_TIMESTAMP=:RUN_DATE ); 
         ROWS_UNCHANGED := :TOTAL_ROWS_IN_PREFINAL - (:ROWS_INSERTED + :ROWS_UPDATED);
		 
		 
--	UPDATE_STATEMENT:= 
	--CONCAT(''UPDATE DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART DM SET ACTIVATION_FLAG = 9 where loan_no NOT IN (select loan_no from 
	--DISHA_L2_CURATED.HISTORICAL_LOAD.COLL_DUELIST where TO_DATE(extracted_date)  = '''''',:RUN_DATE,'''''' AND DM.ACTIVATION_FLAG = 1)'')
	
	UPDATE_STATEMENT:= 
	CONCAT(''UPDATE DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART DM SET ACTIVATION_FLAG = 9,CURRENT_FLAG = '''''',FALSE,'''''', end_timestamp = '''''',:RUN_DATE,''''''  where activation_flag = 1 and NOT EXISTS (
	select 1 from DISHA_L2_CURATED.HISTORICAL_LOAD.COLL_DUELIST src where TO_DATE(extracted_date)  = '''''',:RUN_DATE,'''''' AND TRIM(DM.loan_no) = TRIM(src.LOAN_NO) )'') ;
	
	--RETURN UPDATE_STATEMENT;
	EXECUTE IMMEDIATE :UPDATE_STATEMENT;
	
		INSERT_STATEMENT:= 
	CONCAT(''INSERT INTO DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART('',
			INSERT_COLUMN_LIST,'')
			SELECT '',
			INSERT_VALUE_LIST,'','''''',:RUN_DATE,'''''',NULL,1,TRUE 
			FROM DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL S
			JOIN DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART T
				ON T.LOAN_NO = S.LOAN_NO
				AND T.ACTIVATION_FLAG = 0
                AND S.BUSINESS_DATE = DATEADD(DAY, -1, TO_DATE('''''',RUN_DATE,''''''))
				AND T.END_TIMESTAMP ='''''',:RUN_DATE,'''''';'');
			--RETURN INSERT_STATEMENT;
	EXECUTE IMMEDIATE :INSERT_STATEMENT;	
	
	--DROP TEMP TABLE
	--DROP TABLE IF EXISTS DISHA_MART_ANALYTICS.COLLECTION_MART.DELINQUENCY_MART_PREFINAL;
	
	
          SELECT CONCAT(
            ''===== DATA LOADING REPORT =====
'',
            ''Process Timestamp: '', :CURR_TIME, ''
'',
            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
'',
            ''Rows Inserted: '', :ROWS_INSERTED, ''
'',
            ''Rows Updated: '', :ROWS_UPDATED, ''
'',
            ''Rows Unchanged: '', :ROWS_UNCHANGED, ''

'',
            ''

'',
            ''Status: SUCCESSFULLY LOADED DATA INTO DELINQUENCY_MART''
        ) INTO :FINAL_OUTPUT;
		
		--INSERT AUDIT INFO INTO TABLE
		DELETE FROM DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON 
		WHERE  PROCEDURE_NAME=:PROC_NAME
		AND	   EXECUTION_DATE=DATE(:CURR_TIME);
		
		INSERT INTO DISHA_MART_ANALYTICS.AUDIT_INFO.DAILY_COUNT_RECON
		(PROCEDURE_NAME, TABLE_NAME, EXECUTION_DATE, PREFINAL_CNT, INSERTED_CNT, UPDATED_CNT, UNCHANGED_CNT,STATUS,START_TIME,END_TIME)
		SELECT :PROC_NAME,:TBL_NAME,DATE(:CURR_TIME),:TOTAL_ROWS_IN_PREFINAL,:ROWS_INSERTED,:ROWS_UPDATED,:ROWS_UNCHANGED,''PASS'',:CURR_TIME,CURRENT_TIMESTAMP;
		
        RETURN FINAL_OUTPUT;
    END IF;
---EXCEPTION
---    WHEN OTHER THEN
---        -- Capture any unexpected errors
---         ERROR_MESSAGE := SQLERRM;
---        
---        -- Prepare error output
---          SELECT CONCAT(
---            ''===== DATA LOADING FAILED =====
---'',
---            ''Error Timestamp: '', :CURR_TIME, ''
---'',
---            ''Total Rows in Prefinal: '', :TOTAL_ROWS_IN_PREFINAL, ''
---'',
---            ''ERROR MESSAGE: '', :ERROR_MESSAGE, ''
---'',
---            ''Status: UNEXPECTED ERROR DURING LOADING''
---        ) INTO :FINAL_OUTPUT;
---
---        RETURN FINAL_OUTPUT;
END';