
--------------R1349	C220
select count(loan_number_new) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION')
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
---------------R1350	C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

---------------R1351	C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1352	C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1353	C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1355 C220
SELECT 
    COUNT(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN LOAN_NUMBER_NEW 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN LOAN_NUMBER_NEW 
          END) AS FINAL_OUTPUT
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
    AND IND_AS_EAD > 0.9
    AND REPORT_DATE = {{report_dates}}
    AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

-------------R1357 C220
SELECT 
    COUNT(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN' 
        THEN LOAN_NUMBER_NEW 
    END) -
    COUNT(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(Customer_type)), '') = 'INDIVIDUAL'
             AND CRE_RH_Tagging IS NULL
             AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION', 'RESALE PROPERTY PURCHASE', 'REPAIR AND RENOVATION LOAN')
        THEN LOAN_NUMBER_NEW 
    END) -
    COUNT(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
             AND (CRE_RH_Tagging IS NOT NULL 
                  OR (UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL))
        THEN LOAN_NUMBER_NEW 
    END) AS final_output
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    REPORT_DATE = {{report_dates}}
    AND IND_AS_EAD > 0.9
    AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
---------------R1360	C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and IND_AS_EAD>0.9
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

--------------422--R1368 C220
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and IND_AS_EAD>0.9
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

-------------------R1370 220

SELECT COUNT(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  AND REPORT_DATE = {{report_dates}}
  AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
  
----------------R1349	C221
SELECT ROUND(COALESCE(sum(HL_bifurcation_of__EAD)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1350	C221
SELECT ROUND(COALESCE(sum(HL_bifurcation_of__EAD)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1351	C221
SELECT ROUND(COALESCE(sum(HL_bifurcation_of__EAD)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

----------------R1352	C221
SELECT  ROUND(COALESCE(sum(HL_bifurcation_of__EAD)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1353	C221
SELECT  ROUND(COALESCE(sum(HL_bifurcation_of__EAD)/10000000,0),2) AS FINAL_OUTPUT 
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

----------------R1355	C221
SELECT 
	ROUND(COALESCE(SUM(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN HL_bifurcation_of__EAD 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN HL_bifurcation_of__EAD 
          END)/10000000,0),2) AS FINAL_OUTPUT
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
    AND IND_AS_EAD > 0.9
    AND REPORT_DATE = {{report_dates}}
    AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
----------------R1357	C221
SELECT 
	ROUND(COALESCE(SUM(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN' 
        THEN HL_bifurcation_of__EAD 
    END),0) -
    COALESCE(SUM(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(Customer_type)), '') = 'INDIVIDUAL'
             AND CRE_RH_Tagging IS NULL
             AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION', 'RESALE PROPERTY PURCHASE', 'REPAIR AND RENOVATION LOAN')
        THEN HL_bifurcation_of__EAD 
    END),0) -
    COALESCE(SUM(DISTINCT CASE 
        WHEN COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
             AND (CRE_RH_Tagging IS NOT NULL 
                  OR (UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL))
        THEN HL_bifurcation_of__EAD 
    END),0),2) AS FINAL_OUTPUT
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    REPORT_DATE = {{report_dates}}
    AND IND_AS_EAD > 0.9
    AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';


---------------R1360	C221
SELECT ROUND(COALESCE(sum(NHL_bifurcation_of__EAD)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE --UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')AND 
COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and IND_AS_EAD>0.9
AND REPORT_DATE={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

----------------R1368	C221
SELECT ROUND(COALESCE(sum(CASE WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' THEN NHL_bifurcation_of__EAD
				WHEN UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND CRE_RH_TAGGING IS  NOT NULL THEN NHL_bifurcation_of__EAD
				END)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE IND_AS_EAD>0.9
AND REPORT_DATE ={{report_dates}}
AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';

-------------------R1370	C221

SELECT ROUND(COALESCE(sum(NHL_bifurcation_of__EAD)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  AND REPORT_DATE = {{report_dates}}
  AND TRIM(Asset_classification_Ind_AS) = 'Stage 3';
-------------------R1372	C221
SELECT ROUND(COALESCE(SUM(ECL)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE IND_AS_EAD>0.9
AND LOAN_NPA_TYPE='NPA'
AND REPORT_DATE = {{report_dates}}
