----------------------R1321 C214
select count(loan_number_new) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION')
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
---------------R1322	C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE')
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
---------------R1323	C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1324 C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('RESALE PROPERTY PURCHASE')
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1325 C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1327 C214
SELECT 
    COUNT(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN LOAN_NUMBER_NEW 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN LOAN_NUMBER_NEW 
          END) AS FINAL_OUTPUT
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
    AND IND_AS_EAD > 0.9
	AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
    AND REPORT_DATE = {{report_dates}};
---------------R1332	C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and IND_AS_EAD>0.9
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1340 C214
SELECT count(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and IND_AS_EAD>0.9
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
-------------------R1342 C214
SELECT COUNT(LOAN_NUMBER_NEW) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
  AND REPORT_DATE = {{report_dates}};
----------------R1321 C215
SELECT ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE', 'CONSTRUCTION')
AND CRE_RH_Tagging is null
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1322 C215
SELECT ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('PURCHASE')
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1323 C215
SELECT ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1324 C215
SELECT  ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND CRE_RH_Tagging is null
AND UPPER(TRIM(NHB_PRODUCT)) IN ('RESALE PROPERTY PURCHASE')
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1325 C215
SELECT  ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2) AS FINAL_OUTPUT 
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0
AND REPORT_DATE ={{report_dates}};
----------------R1327 C215
SELECT 
    ROUND(COALESCE(SUM(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN HL_bifurcation_of__EAD 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN REPAYMENT_DURING_MONTH 
          END)/10000000,0),2) AS FINAL_OUTPUT
FROM 
    DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE 
    COALESCE(UPPER(TRIM(NHB_PRODUCT)), '') <> 'OTHER LOAN'
    AND IND_AS_EAD > 0.9
    AND REPORT_DATE = {{report_dates}}
	AND COALESCE(REPAYMENT_DURING_MONTH,0)>0;
---------------R1332	C215
SELECT ROUND(COALESCE(sum(REPAYMENT_DURING_MONTH)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN  ('OTHER LOAN')AND 
COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and IND_AS_EAD>0.9
AND REPORT_DATE ={{report_dates}}
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0;

----------------R1340 C215
SELECT ROUND(COALESCE(sum(CASE WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' THEN REPAYMENT_DURING_MONTH
				WHEN UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND CRE_RH_TAGGING IS  NOT NULL THEN REPAYMENT_DURING_MONTH
				END)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE IND_AS_EAD>0.9
AND UPPER(TRIM(NHB_PRODUCT)) IN ('OTHER LOAN')
AND REPORT_DATE ={{report_dates}}
AND COALESCE(REPAYMENT_DURING_MONTH,0)>0;
-------------------R1342 C215
SELECT ROUND(COALESCE(COALESCE(sum(REPAYMENT_DURING_MONTH),0)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.OUTSTANDING_MART
WHERE UPPER(TRIM(NHB_PRODUCT)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  AND REPORT_DATE = {{report_dates}}
  AND COALESCE(REPAYMENT_DURING_MONTH,0)>0;
 
 