

--------------R1271	C204
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND REPORT_DATE ={{report_dates}};
--------------R1272	C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}};
---------------------------------------------------------------------
--------------R1273	C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
--AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}};
--------------R1274	C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1275	C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}};

----------------R1277 C204
SELECT 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES = 0 
         AND LOAN_AUTHOR_DATE >= '2025-04-01'
        THEN 1 
    END) - 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES <> 0
        THEN 1 
    END) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};
********************************DONE
----------------R1290 C204
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};

-------------------R1292 C204

SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND REPORT_DATE = {{report_dates}};
  
  
--------------R1271	C205
select ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND REPORT_DATE ={{report_dates}};
--------------R1272	C205
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1273	C205
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
--AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}};
--------------R1274	C205
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1275	C205
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}};

----------------R1277 C205
SELECT  
    ROUND(COALESCE(SUM(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN HL_BIFUR_OF_SANCTION_AMT 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN HL_BIFUR_OF_SANCTION_AMT 
          END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C205
SELECT ROUND(COALESCE(sum(case 
    when UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' THEN NHL_BIFUR_OF_SANCTION_AMT
    when UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_TAGGING is not null  THEN NHL_BIFUR_OF_SANCTION_AMT end
    )/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE  REPORT_DATE ={{report_dates}};

----------------R1290 C205--------------------
SELECT ROUND(COALESCE(sum(CASE WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' THEN NHL_BIFUR_OF_SANCTION_AMT
				WHEN UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND CRE_RH_TAGGING IS  NOT NULL THEN NHL_BIFUR_OF_SANCTION_AMT
				END)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};
-------------------R1292 C205
SELECT ROUND(COALESCE(sum(NHL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND REPORT_DATE = {{report_dates}};

--------------R1271	C202
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1272	C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
---------------------------------------------------------------------
--------------R1273	C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
--AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1274	C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1275	C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};

----------------R1277 C202
SELECT 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES = 0 
         AND LOAN_AUTHOR_DATE >= '2025-04-01'
        THEN 1 
    END) - 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES <> 0
        THEN 1 
    END) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and coalesce(loan_amount,0)<>0
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
********************************DONE
----------------R1290 C202
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};

-------------------R1292 C202

SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
  AND REPORT_DATE = {{report_dates}};
  
  
--------------R1271	C203
select ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1272	C203
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1273	C203
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
--AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}};
--------------R1274	C203
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
--------------R1275	C203
SELECT ROUND(COALESCE(sum(HL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};

----------------R1277 C203
SELECT  
    ROUND(COALESCE(SUM(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL THEN HL_BIFUR_OF_SANCTION_AMT 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL THEN HL_BIFUR_OF_SANCTION_AMT 
          END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C203
SELECT ROUND(COALESCE(sum(case 
    when UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' THEN NHL_BIFUR_OF_SANCTION_AMT
    when UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_TAGGING is not null  THEN NHL_BIFUR_OF_SANCTION_AMT end
    )/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};

----------------R1290 C203--------------------
SELECT ROUND(COALESCE(sum(CASE WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' THEN NHL_BIFUR_OF_SANCTION_AMT
				WHEN UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND CRE_RH_TAGGING IS  NOT NULL THEN NHL_BIFUR_OF_SANCTION_AMT
				END)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
AND REPORT_DATE ={{report_dates}};
-------------------R1292 C203
SELECT ROUND(COALESCE(sum(NHL_BIFUR_OF_SANCTION_AMT)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)=DATE_TRUNC('MONTH',DATE{{report_dates}})
  AND REPORT_DATE = {{report_dates}};
  
  
--------------R1271	C200
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND REPORT_DATE ={{report_dates}};
--------------R1272	C200
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1273	C200

select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}};
--------------R1274	C200
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1275	C200
select count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}};

----------------R1277 C200
SELECT 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES = 0 
         AND LOAN_AUTHOR_DATE >= '2025-04-01'
		 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}})
        THEN 1 
    END) - 
    COUNT(CASE 
        WHEN (CRE_RH_Tagging IS NOT NULL OR 
              (CRE_RH_Tagging IS NULL AND UPPER(TRIM(Customer_type)) = 'CORPORATE'))
         AND TAGGING_OF_CANCELLED_CASES <> 0
		 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}})
        THEN 1 
    END) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C200
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}})  THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
AND CRE_RH_TAGGING IS  NULL
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};

----------------R1290 C200
SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};

-------------------R1292 C200

SELECT count(case when TAGGING_OF_CANCELLED_CASES =0 and LOAN_AUTHOR_DATE>='2025-04-01' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)-
count(case when TAGGING_OF_CANCELLED_CASES <>0 AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN loan_number_new end)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND REPORT_DATE = {{report_dates}};
  
  
--------------R1271	C201
select ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2)
AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1  
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE', 'CONSTRUCTION')
AND REPORT_DATE ={{report_dates}};
--------------R1272	C201
SELECT ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(Transaction_structure)) IN ('BUILDER_PURCHASE', 'GENERAL_APF')
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1273	C201
SELECT ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(SYSTEM_PRODUCT)) = 'PURCHASE AND CONSTRUCTION'
AND REPORT_DATE ={{report_dates}};
--------------R1274	C201
SELECT ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND CRE_RH_Tagging is null
AND UPPER(TRIM(PRODUCT_NHB)) IN ('RESALE PROPERTY PURCHASE')
AND REPORT_DATE ={{report_dates}};
--------------R1275	C201
SELECT ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(Customer_type)),'') = 'INDIVIDUAL'
and coalesce(loan_amount,0)<>0
AND UPPER(TRIM(PRODUCT_NHB)) IN ('REPAIR AND RENOVATION LOAN')
AND CRE_RH_Tagging is null
AND REPORT_DATE ={{report_dates}};

----------------R1277 C201
SELECT  
    ROUND(COALESCE(SUM(CASE 
            WHEN CRE_RH_Tagging IS NOT NULL AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT 
            WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_Tagging IS NULL AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN HL_BIFUR_OF_SANCTION_AMT 
          END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE COALESCE(UPPER(TRIM(PRODUCT_NHB)), '') <> 'OTHER LOAN'
  AND COALESCE(loan_amount,0) <> 0
  AND REPORT_DATE = {{report_dates}};

---------------R1282	C201
SELECT ROUND(COALESCE(sum(case 
    when UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN NHL_BIFUR_OF_SANCTION_AMT
    when UPPER(TRIM(Customer_type)) = 'CORPORATE' AND CRE_RH_TAGGING is not null AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN NHL_BIFUR_OF_SANCTION_AMT end
    )/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE  REPORT_DATE ={{report_dates}};

----------------R1290 C201--------------------
SELECT ROUND(COALESCE(sum(CASE WHEN UPPER(TRIM(Customer_type)) = 'CORPORATE' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN NHL_BIFUR_OF_SANCTION_AMT
				WHEN UPPER(TRIM(Customer_type)) = 'INDIVIDUAL' AND DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) AND CRE_RH_TAGGING IS  NOT NULL THEN NHL_BIFUR_OF_SANCTION_AMT
				END)/10000000,0),2)  AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN  ('OTHER LOAN')
AND COALESCE(UPPER(TRIM(Customer_type)),'') = 'CORPORATE'
and coalesce(loan_amount,0)<>0
AND REPORT_DATE ={{report_dates}};
-------------------R1292 C201
SELECT ROUND(COALESCE(sum(CASE WHEN DATE_TRUNC('MONTH',LOAN_AUTHOR_DATE)<DATE_TRUNC('MONTH',DATE{{report_dates}}) THEN  NHL_BIFUR_OF_SANCTION_AMT END)/10000000,0),2) AS FINAL_OUTPUT
FROM DISHA_MART_ANALYTICS.REGULATORY_MART.SANCTION_PERIOD_MART_V1
WHERE UPPER(TRIM(PRODUCT_NHB)) IN ('OTHER LOAN')
  AND COALESCE(UPPER(TRIM(Customer_type)),'') NOT IN ('INDIVIDUAL', 'CORPORATE')
  and coalesce(loan_amount,0)<>0
  AND REPORT_DATE = {{report_dates}};
